### ISSUE TITLE
[Priority: low]Cloud storage

### ISSUE THREAD

**Issue by mm90849491** [mm90849491/CoopR-S#10]
Integrate providers like Dropbox, Google, Amazon, Box.net (API)
There are two ways to assign the storage:
1. make the storage public to the entire web
2. each user has its own account from those providers

**Comment by jpotusek** [comment]
finished filepicker. Meng can you merge the cloudstorage branch

**Comment by mm90849491** [comment]
I want to know how pull request works. Can you somehow try to make a pull
request on Github? I will merge it anyway.

**Comment by jpotusek** [comment]
pull doesnt show up as anything for me, since when I pull I get "already up to date" message

**Comment by mm90849491** [comment]
I believe you need to compare your branch to an out of data branch like
master, then you will have an option to send a "pull request" to inform the
branch owner to update files from your branch.
If it takes more time than reply the issue, we can ignore this
functionality.
