### ISSUE TITLE
[Priority: low]PDF creator

### ISSUE THREAD

**Issue by mm90849491** [mm90849491/CoopR-S#13]
PDF generation (Prawn gem)  _recommend_
or
HTML to PDF converter

**Comment by icwong** [comment]
Hey Justin, I'll be working on this since you gave me the permission to work on it yesterday

**Comment by mm90849491** [comment]
Finished the pdf creator to covert the list postings (review/promotion) html into a PDF copy. Need permission to create a branch.

**Comment by icwong** [comment]
Finished the pdf creator to covert the list postings (review/promotion) html into a PDF copy. Need permission to create a branch.

My fault for using your account Meng. It was still logged onto my computer.

**Comment by mm90849491** [comment]
Make a public repo, send the link and show me you can do branching.

**Comment by icwong** [comment]
Sure,

https://github.com/icwong/testBranches/network

I even created a branch off a branch.

----- Original Message -----

**Comment by icwong** [comment]
Should be good to go https://github.com/mm90849491/CoopR-S/tree/pdf

Please merge it into master.

Please delete the pdfPrawn. I accidently created a branch off my test rails web application.
