### ISSUE TITLE
gem faker

### ISSUE THREAD

**Issue by mm90849491** [mm90849491/CoopR-S#2]
see jpotusek's comment below

**Comment by icwong** [comment]
Hey guys,

I spent four hours just figuring out how to click login from the side navigation bar and popup the login/register with no luck.

Should I just design the redirect link page isntead?

Anyone can help figure this out?

**Comment by AmberQi1412** [comment]
I think just the redirect link page is good enough.

----- Original Message -----

**Comment by icwong** [comment]
Sorry guys, but I spent way too long on this.

I have to start studying for the 276 and 320 midterm.

I'll fix this issue and complete the front end after my exams.

By the way, has anyone tested the register if it works correctly?

----- Original Message -----

**Comment by jpotusek** [comment]
there is a problem with registration when redirected to the invalid input page, you can't register. the input field ids change from user_password to student_password etc

**Comment by mm90849491** [comment]
Can you post what kind of inputs will reproduce that situation?

**Comment by jpotusek** [comment]
if I only enter a password and click sign-up, it takes me to a new signup page with the invalid message and then valid inputs cannot register and hits an error page when I click sign up again.

**Comment by AmberQi1412** [comment]
It seems that after getting error when sign-up, it directs to /users other than /users/sign_up

----- Original Message -----

**Comment by mm90849491** [comment]
I am going to finish the Post class first. The worst case is we test input from client side using javascript, the user email can be checked by an extra "email available?" button to enforce the uniqueness.
If you have time to work on this, you can try parsing the parameters (registrations_controller.rb =>sign_up_params & account_update_params) so it accepts more general class, or somehow reroute this thing back to sign_up.

**Comment by mm90849491** [comment]
Bug fixed accidentally, while I was doing Post class.
Change[<app-dir>/app/views/users/registrations/new.html.erb]:
<%= form_for @user, url: {action: "create"} do |f| %>
<%= form_for @user, as: :user, url: {action: "create"} do |f| %>
