### ISSUE TITLE
[Priority: low]More informative password bar

### ISSUE THREAD

**Issue by mm90849491** [mm90849491/CoopR-S#4]
TODO: actual score on the top of password bar like this

---

|______3______|

+Show a full message what kind of password requirement on mouse hover? 
+Mini game that user can play with this bar?

**Comment by icwong** [comment]
Hey guys,

Just a reminder we need to submit our git and heroku web app and document into coursys.

Would you guys mind telling me what the we have done so far so we can compile a document and send it

Ivan:
- User interface mockup design (png samples)
- Created a side bar navigation
- Created a clickable that pulls out

**Comment by icwong** [comment]
Here is iteration 1 requirements:

In iteration 1, you must include stories for login and views based on user role must be included in the
first version as minimum requirements, and can be expanded for future iterations. You should
implement the login from scratch and not using gems (you may change this in later iterations). This
means that you should have several types of users. Each type of user should be able to login to your
system and be presented with their own view. For example, an admin user may be able to login and
view every user in the database whereas a normal user may not have that ability. 

----- Original Message -----
From: "Ivan Wong" <icwong@sfu.ca>
To: "mm90849491/CoopR-S" <reply@reply.github.com>
Cc: "mm90849491/CoopR-S" <CoopR-S@noreply.github.com>
Sent: Monday, June 20, 2016 12:01:49 AM
Subject: CoopR-S - Submission Documents

Hey guys,

Just a reminder we need to submit our git and heroku web app and document into coursys.

Would you guys mind telling me what the we have done so far so we can compile a document and send it

Ivan:
- User interface mockup design (png samples)
- Created a side bar navigation
- Created a clickable that pulls out

**Comment by mm90849491** [comment]
DO NOT REPLY ANY IRRELEVANT CONTENT TO THE *ISSUE THREAD*
<https://github.com/mm90849491/CoopR-S/issues/4>

**Comment by mm90849491** [comment]
For some reason password bar does not show on IE.
Not a big problem, as IE is always an outlying creature and could be ignored.

**Comment by jpotusek** [comment]
Justin:

-validate registration forms

-display password strength meter


________________________________

**Comment by jpotusek** [comment]
http://www.w3schools.com/tags/tag_meter.asp
claims that the meter tag should work on IE 13.0+
it's a feature new to HTML5

**Comment by jpotusek** [comment]
changed the meter type, score is ontop of bar and now works in IE

**Comment by jpotusek** [comment]
added password hint on hover
