### ISSUE TITLE
[bug] compare posts pdf

### ISSUE THREAD

**Issue by jpotusek** [mm90849491/CoopR-S#53]
shows html code in post area instead of plain text

**Comment by mm90849491** [comment]
I would say the pdf generator is far from complete, someone needs to learn Prawn language and manually modify the pdf format.
e.g. scan <p></p>, replace <b></b> to style: :bold

**Comment by jpotusek** [comment]
i was trying to work on this possibly using strip_tags() built into rails,
but compare is broken right now
