### ISSUE TITLE
[priority: low] check off valid form inputs

### ISSUE THREAD

**Issue by jpotusek** [mm90849491/CoopR-S#6]
show message that the confirmation password does not match first password entry

**Comment by mm90849491** [comment]
I think a check mark (✓) is informative enough to indicate input is acceptable, and we might check every input boxes before the form is submitted, as the respond time is quite long.

**Comment by jpotusek** [comment]
I'll give this one a try

**Comment by mm90849491** [comment]
I will assign this issue to Justin immediately as he did the input validation part in iteration 0.

**Comment by jpotusek** [comment]
the form elements are checked off when it as valid inputs as well as outlining in red or green depending on validity
